### ISSUE TITLE
not captable with vite in esModule system

### ISSUE THREAD

**Issue by cdll** [cytoscape/cytoscape.js-dagre#110]
as I tried 

```js
import cytoscape from 'cytoscape';
import dagre from 'cytoscape-dagre';

cytoscape.use( dagre );
```
 I got this `Error` in browser:
```shell
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Graph')
    at ../../node_modules/.pnpm/cytoscape-dagre@2.3.2_cytoscape@3.18.3/node_modules/cytoscape-dagre/node_modules/dagre/lib/greedy-fas.js (greedy-fas.js:2:13)
    at __require2 (chunk-S5KM4IGW.js?v=03374713:18:50)
    at ../../node_modules/.pnpm/cytoscape-dagre@2.3.2_cytoscape@3.18.3/node_modules/cytoscape-dagre/node_modules/dagre/lib/acyclic.js (acyclic.js:4:17)
    at __require2 (chunk-S5KM4IGW.js?v=03374713:18:50)
    at ../../node_modules/.pnpm/cytoscape-dagre@2.3.2_cytoscape@3.18.3/node_modules/cytoscape-dagre/node_modules/dagre/lib/layout.js (layout.js:4:15)
    at __require2 (chunk-S5KM4IGW.js?v=03374713:18:50)
    at ../../node_modules/.pnpm/cytoscape-dagre@2.3.2_cytoscape@3.18.3/node_modules/cytoscape-dagre/node_modules/dagre/index.js (index.js:26:11)
    at __require2 (chunk-S5KM4IGW.js?v=03374713:18:50)
    at webpackUniversalModuleDefinition (cytoscape-dagre.js:3:28)
    at ../../node_modules/.pnpm/cytoscape-dagre@2.3.2_cytoscape@3.18.3/node_modules/cytoscape-dagre/cytoscape-dagre.js (cytoscape-dagre.js:10:1)
```

**Comment by cdll** [comment]
(the Error is shown in a `Promise` because I ran into the error at first, so I tried to load the module async with `import()` so that my page could show up anyway)

Is there a minified version that I could use?
