### ISSUE TITLE
A ERROR

### ISSUE THREAD

**Issue by yangdaxian-is-cool** [cytoscape/cytoscape.js-dagre#127]
greedy-fas.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'Graph')
    at requireGreedyFas (greedy-fas.js:2:34)
    at requireAcyclic (acyclic.js:4:17)
    at requireLayout (layout.js:4:15)
    at requireDagre (index.js:26:11)
    at webpackUniversalModuleDefinition (cytoscape-dagre.js:3:28)
    at cytoscape-dagre.js:10:1
    at cytoscape-dagre.js:397:2
![微信截图_20240411165123](https://github.com/cytoscape/cytoscape.js-dagre/assets/76930408/28b87235-d2bf-4714-b312-c89aa3841f7f)
![微信截图_20240411165150](https://github.com/cytoscape/cytoscape.js-dagre/assets/76930408/867f0d71-a439-4f3e-84c6-35f3195733a3)

**Comment by yangdaxian-is-cool** [comment]
this error happen when import a component with cytoscape
